google.load("feeds","1");
function writeGatcha(a,b,c,d,g){if(void 0===b||null==b)b="side-";if(void 0===g||null==g||1!=g)g=!1;var f=null;if("category"==c){var e=document.querySelectorAll("div.categories a");if(null!=e&&0<e.length){for(var f=[],h=0;h<e.length;h++){var k=e[h].href,l=k.replace(getBlogUrl(),"");console.log(l);0>l.indexOf("-")&&0<=k.indexOf(getBlogUrl()+"/archive/category/")&&f.push(e[h])}h=Math.floor(Math.random()*f.length);f=f[h]}}e="";e=void 0!==f&&null!=f?f.href.replace(getBlogUrl()+"/archive/category/",""):
"all"==c?"gatcha-all":"recent"==c?"gatcha-new":"";void 0!==d&&null!=d?(document.write('<span class="hatena-module-foot"><h3>'+d),500<window.innerWidth?(document.write('<span style="float:right">'),writeForm(b,e,a,g),document.write("</span></h3>")):(document.write("</h3>"),writeForm(b,e,a)),document.write("</span>")):writeForm(b,e,a);document.write('<span id="'+b+'gachaSpan"></span>');switchGatchButton(!1,b)}
function writeForm(a,b,c,d){document.write('<select id="'+a+'inGatchaCategory" onchange="runGatcha(\''+a+'\')" style="width:150px;"><select>');document.write(' <input type="button" id="'+a+'btnNormalGatcha" value=" \u66f4\u65b0 " onClick="runGatcha(\''+a+"')\" />");document.write(' <input type="button" id="'+a+'btnMoveGatcha" value=" \u4e00\u89a7 " onClick="moveGatcha(\''+a+"')\" />");d&&document.write(' <input type="button" id="'+a+'btnFeedlyGatcha" value=" \u8cfc\u8aad " onClick="feedGatcha(\''+
a+"')\" />");document.write('<input type="hidden" id="'+a+'inGatchaNum" value="'+c+'" />');document.write('<input type="hidden" id="'+a+'mode" value="'+b+'" />');a=document.getElementById(a+"inGatchaCategory");a.appendChild(createOption("gatcha-all","\u5168\u3066"));a.appendChild(createOption("gatcha-rare","\u4eba\u6c17"));a.appendChild(createOption("gatcha-new","\u6700\u65b0"));a.selectedIndex=1}
function writeGatchaCategory(a){if(void 0===a||null==a)a="side-";var b=getBlogUrl(),c=new google.feeds.Feed("http://pipes.yahoo.com/pipes/pipe.run?&blog="+b+"&_id=31da73e0525591d9dd0c0702856a3b5b&_render=rss");c.setNumEntries(100);c.load(function(d){var c=document.getElementById(a+"inGatchaCategory"),f=[];!d.error&&0<d.feed.entries.length&&(f=d.feed.entries);for(d=0;d<f.length;d++){var e=f[d];0<=e.link.replace(getBlogUrl(),"").indexOf("-")||(e=createOption(e.link.replace(b+"/category/",""),e.title),
c.appendChild(e))}console.log(c);f=!1;e=document.getElementById(a+"mode");for(d=0;d<c.options.length;d++)if(c.options[d].value==e.value){f=c.options[d].selected=!0;break}f||null==e.value||""==e.value||(d=e.value.replace(b+"/archive/category/",""),e=createOption(d,decodeURI(d)),c.appendChild(e),e.selected=!0);runGatcha(a)})}function createOption(a,b){var c=document.createElement("option");c.value=a;c.text=b;return c}
function switchGatchButton(a,b){document.getElementById(b+"btnNormalGatcha").disabled=!a;document.getElementById(b+"btnMoveGatcha").disabled=!a;document.getElementById(b+"inGatchaCategory").disabled=!a;var c=document.getElementById(b+"btnFeedlyGatcha");null!=c&&(c.disabled=!a)}
function feedGatcha(a){switchGatchButton(!1,a);var b="",b=getBlogUrl(),c=document.getElementById(a+"inGatchaCategory"),d=c.selectedIndex,b=0==d||2==d?b+"/feed":1==d?"http://b.hatena.ne.jp/entrylist?sort=count&mode=rss&url="+encodeURIComponent(b):b+"/rss/category/"+c.value;switchGatchButton(!0,a);window.open("http://cloud.feedly.com/#subscription%2Ffeed%2F"+encodeURIComponent(b))}
function moveGatcha(a){switchGatchButton(!1,a);var b="",b=getBlogUrl(),c=document.getElementById(a+"inGatchaCategory"),d=c.selectedIndex,b=0==d||2==d?b+"/archive":1==d?"http://b.hatena.ne.jp/entrylist?sort=count&url="+encodeURIComponent(b):b+"/archive/category/"+c.value;switchGatchButton(!0,a);location.href=b}
function runGatcha(a){switchGatchButton(!1,a);var b=document.getElementById(a+"inGatchaCategory"),c=b.selectedIndex;0==c?runNormalGatcha(a):1==c?runRareGatcha(a):2==c?runNewGatcha(a):runCategoryGatcha(a,b.value);switchGatchButton(!0,a)}
function runCommonGatcha(a,b){var c=document.getElementById(a+"inGatchaNum").value,d=new google.feeds.Feed(b);d.setNumEntries(50);d.load(function(b){var d=[];!b.error&&0<b.feed.entries.length&&(d=b.feed.entries);d=removeThisEntry(d);b=document.getElementById(a+"gachaSpan");createOwnHtml(b,null,d,null,c)})}function runNewGatcha(a){var b=getBlogUrl();runCommonGatcha(a,b+"/rss")}
function runRareGatcha(a){var b=getBlogUrl(),b="http://b.hatena.ne.jp/entrylist?sort=count&mode=rss&url="+encodeURIComponent(b);runCommonGatcha(a,b)}function runCategoryGatcha(a,b){var c=getBlogUrl()+"/rss/category/"+b;runCommonGatcha(a,c)}
function runNormalGatcha(a){for(var b=document.getElementById(a+"inGatchaNum").value,c=getBlogUrl(),d=[],g=1;10>=g;g++){var f="http://pipes.yahoo.com/pipes/pipe.run?url="+encodeURIComponent(c+"/sitemap.xml?page="+g)+"&_id=f48751a13b81b177ba69aa786f7354bf&_render=rss";d.push(new google.feeds.Feed(f))}for(var e=[],h=0,g=0;g<d.length;g++)d[g].setNumEntries(100),d[g].load(function(c){c.error||0==c.feed.entries.length||(e=e.concat(c.feed.entries));++h==d.length&&(e=removeThisEntry(e),c=document.getElementById(a+
"gachaSpan"),createOwnHtml(c,null,e,null,b))})};