function writeGatcha(a,b,c,h,f){if(void 0===b||null==b)b="side-";if(void 0===f||null==f||1!=f)f=!1;var d=null;if("category"==c&&(c=document.querySelectorAll("div.categories a"),null!=c&&0<c.length)){for(var d=[],e=0;e<c.length;e++){var g=c[e].href;0>g.replace(getBlogUrl(),"").indexOf("-")&&0<=g.indexOf(getBlogUrl()+"/archive/category/")&&d.push(c[e])}e=Math.floor(Math.random()*d.length);d=d[e]}c="";c=void 0!==d&&null!=d?d.href.replace(getBlogUrl()+"/archive/category/",""):"";void 0!==h&&null!=h?(document.write('<span class="hatena-module-foot"><h3>'+
h),500<window.innerWidth?(document.write('<span style="float:right">'),writeForm(b,c,a,f),document.write("</span></h3>")):(document.write("</h3>"),writeForm(b,c,a)),document.write("</span>")):writeForm(b,c,a);document.write('<span id="'+b+'gachaSpan"></span>');switchGatchButton(!1,b)}
function writeForm(a,b,c,h){document.write('<select id="'+a+'inGatchaCategory" onchange="runGatcha(\''+a+'\')" style="width:150px;"><select>');document.write(' <input type="button" id="'+a+'btnNormalGatcha" value=" \u66f4\u65b0 " onClick="runGatcha(\''+a+"')\" />");document.write(' <input type="button" id="'+a+'btnMoveGatcha" value=" \u4e00\u89a7 " onClick="moveGatcha(\''+a+"')\" />");h&&document.write(' <input type="button" id="'+a+'btnFeedlyGatcha" value=" \u8cfc\u8aad " onClick="feedGatcha(\''+
a+"')\" />");document.write('<input type="hidden" id="'+a+'inGatchaNum" value="'+c+'" />');document.write('<input type="hidden" id="'+a+'mode" value="'+b+'" />');a=document.getElementById(a+"inGatchaCategory");a.appendChild(createOption("gatcha-new","\u6700\u65b0"));a.selectedIndex=0}
function writeGatchaCategory(a){if(void 0===a||null==a)a="side-";var b=getBlogUrl(),c=document.getElementById(a+"inGatchaCategory"),b=document.getElementById(a+"mode").value.replace(b+"/archive/category/",""),b=createOption(b,decodeURI(b));c.appendChild(b);b.selected=!0;runGatcha(a)}function createOption(a,b){var c=document.createElement("option");c.value=a;c.text=b;return c}
function switchGatchButton(a,b){document.getElementById(b+"btnNormalGatcha").disabled=!a;document.getElementById(b+"btnMoveGatcha").disabled=!a;document.getElementById(b+"inGatchaCategory").disabled=!a;var c=document.getElementById(b+"btnFeedlyGatcha");null!=c&&(c.disabled=!a)}
function feedGatcha(a){switchGatchButton(!1,a);var b="",b=getBlogUrl(),c=document.getElementById(a+"inGatchaCategory"),b=0==c.selectedIndex?b+"/feed":b+"/rss/category/"+c.value;switchGatchButton(!0,a);window.open("http://cloud.feedly.com/#subscription%2Ffeed%2F"+encodeURIComponent(b))}
function moveGatcha(a){switchGatchButton(!1,a);var b="",b=getBlogUrl(),c=document.getElementById(a+"inGatchaCategory"),b=0==c.selectedIndex?b+"/archive":b+"/archive/category/"+c.value;switchGatchButton(!0,a);location.href=b}function runGatcha(a){switchGatchButton(!1,a);var b=document.getElementById(a+"inGatchaCategory");0==b.selectedIndex?runNewGatcha(a):runCategoryGatcha(a,b.value);switchGatchButton(!0,a)}
function runCommonGatcha(a,b){var c=document.getElementById(a+"inGatchaNum").value;$.ajax({url:b,type:"get",dataType:"xml",timeout:5E3,success:function(b,f){if("success"===f){var d=0,e=[],g;$(b).find("item").each(function(){e[d]={};$(this).children().each(function(){g=$(this)[0].nodeName;e[d][g]={};attributes=$(this)[0].attributes;for(var a in attributes)e[d][g][attributes[a].name]=attributes[a].value;e[d][g].text=$(this).text()});d++});var k=[],l;for(l in e){var m={};m.link=e[l].link.text;k.push(m)}k=
removeThisEntry(k);l=document.getElementById(a+"gachaSpan");createOwnHtml(l,null,k,null,c)}}})}function runNewGatcha(a){var b=getBlogUrl();runCommonGatcha(a,b+"/rss")}function runCategoryGatcha(a,b){var c=getBlogUrl()+"/rss/category/"+b;runCommonGatcha(a,c)};
